### ISSUE TITLE
Sinopia upstream changes for bfe.js

### ISSUE THREAD

**Issue by jermnelson** [lcnetdev/bfe#33]
Currently LOC uses `builds/bfe.dev.js` for active development. This seems counter to suggested software development practice when using [Grunt](https://gruntjs.com/sample-gruntfile#requirements) where code editing occurs in `src` or `app`  and the distribution files are located in the `build` including the minified versions of the source code (both javascript and css to start). 

Extending the existing `Grunt.js` grunt file, the current **master** branch of Sinopia BFE (based on the LOC **development** branch) has moved the `builds/bfe.dev.js` to `src/bfe.js`. The files in the builds directory are not under source control but instead are generated with the *default* grunt task. 

As the Sinopia development ramps up, we have started deconstructing the **bfe** code base to be more modular for better change management, programmer coordination, and testing coverage. We would still like to continue to pull in upstreams changes but would propose that LOC merge our changes and start developing on the `src/bfe.js` to facilitate continued collaboration moving forward. If this agreeable, we can do a pull request from Sinopia but would require manual merging of the most recent commits of **bfe**. 

If it would help, I would be happy to do a conference call to explain these changes in more detail.

**Comment by kirkhess** [comment]
Hi Jeremy - here's the related changes I have planned for next week:
- Put bfe.dev.js changes into src files - I know bfe.js, src/bfelookups.js and src/bfestore.js and build_support/mini_require.js have changes (I don't think bfelogging.js changed)
These are the files that are concatenated with grunt into builds/bfe.js & minified into builds/bfe.min.js
- Update index.html and development.html & static/js/config-dev.js and static/js/config.js*
- I rebased master in May w/0.3.0 before we started this project so I'm just going to merge development into master
- delete bfe.dev.js.
- create release v.0.4.0
- delete development branch (going forward there will only be master and various feature branches)

* Note: config-dev.js and development.html have been there all along, the intent for dev was logging on debug and non-minified bfe.js. 

I think you might want to wait a few days before making any sinopia/bfe changes since I think you'll have a better starting point to start deconstructing the bfe code & CI/CD. Also, I would also be happy to talk on the phone with all the developers so we're all on the same page, probably a separate call than our Tues one? Thanks!

**Comment by jermnelson** [comment]
Thanks Kirk, those changes sound good. I'll wait and merge your changes when they are available. Our development sprint will likely start in a couple of weeks so having a meeting between you and the developers at Stanford would be good and would likely be separate from the Tuesday meeting.

**Comment by kirkhess** [comment]
Released v0.4.0 & the fork is based on master so we should be good to go forward.
